Repository srm-kzilla/kzilla.xyz, pull requests merged in 2022-08, with the labels that each got.

#196 💄 feat:(mylinks) Redesign `MyLinks` page
  client/src/components/NavbarStructure.svelte
  client/src/myLinksPage/MyLinks.svelte
  client/src/myLinksPage/Table.svelte
  public/icons/analytics.svg
  public/icons/copy.svg
  public/icons/edit.svg
  public/icons/option.svg
  public/icons/qr.svg
  public/icons/settings.svg
Labels: enhancement, ui, frontend

#195 :sparkles: added qr functionality to home page
  client/src/homePage/FormStructure.svelte
Labels: enhancement, frontend

#197 Fix Validate URL Regex
  client/src/homePage/FormStructure.svelte
Labels: bug, frontend

#202 feat: Dynamic button, change `customCode` minimum length, minor fixes
  api/constants.ts
  api/models/joi-schemas.ts
  api/services/analytics-service.ts
  api/utils/analytics-helpers.ts
  client/src/analyticsPage/Analytics.svelte
  client/src/analyticsPage/HeroTag.svelte
  client/src/components/Button.svelte
  client/src/homePage/FormStructure.svelte
  client/src/myLinksPage/Table.svelte
  public/icons/copy-light.svg
Labels: bug, ui, backend, frontend

#203 :bug: fixed https in qr
  client/src/homePage/FormStructure.svelte
  client/src/myLinksPage/Table.svelte
  yarn.lock
Labels: bug, enhancement, frontend

#204 Move Domain URL to env
  .env.example
  client/package-lock.json
  client/package.json
  client/rollup.config.js
  client/src/constants.js
  client/src/homePage/FormStructure.svelte
  package.json
Labels: enhancement, frontend

#205 :bug: fix: site changes layout on keyboard show
  client/src/components/Button.svelte
  client/src/homePage/FormStructure.svelte
Labels: bug, ui, frontend
