Repository srm-kzilla/kzilla.xyz, pull requests merged in 2022-07, with the labels that each got.

#193 ✨ feat: custom code support
  api/constants.ts
  api/controllers/link-controller.ts
  api/errors.ts
  api/models/joi-schemas.ts
  api/routes/link-routes.ts
  api/routes/webhook-routes.ts
Labels: enhancement, backend

#192 ✨ added toast notification
  client/package-lock.json
  client/package.json
  client/src/constants.js
  client/src/homePage/FormStructure.svelte
  client/src/myLinksPage/Table.svelte
  yarn.lock
Labels: enhancement, frontend

#194 💄feat: (custom-code) ui changes for custom code support
  client/src/components/Button.svelte
  client/src/components/NavbarStructure.svelte
  client/src/homePage/FormStructure.svelte
  client/src/services/APIservice.js
Labels: enhancement, ui
